---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.web-container: semver:~3.1
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: tmeyers77/my-images:toddtired
        resources:
        ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
